SELECT DIS.ID AS DIS_ID , DIS.BIBLIOGRAFIA AS DIS_BIBLIOGRAFIA,
       DIS.CARGAhORARIA AS DIS_CARGA_HORARIA, DIS.CURSO AS DIS_CURSO,
       DIS.DISTRIBUICAOaVALIACAO AS DIS_DISTRIBUICAO_AVALIACAO,
       DIS.EMENTA AS DIS_EMENTA, DIS.NOME AS DIS_NOME,
       DIS.OBSERVACAO AS DIS_OBSERVACAO, DIS.TIPO AS DIS_TIPO,
       PES_PROF.ID AS PROF_ID, PES_PROF.NOME AS PROF_NOME,
       PES_PROF.CPF AS PROF_CPF, PES_ALU.NOME AS ALU_NOME,
       ALU.MATRICULA AS ALU_MATRICULA, SAL.ID AS SAL_ID, SAL.CAPACIDADE AS SAL_CAPACIDADE,
       SAL.DATA_TERMINO_MANUTENCAO AS SAL_DATA_TERMINO_MANUT,
       SAL.POSSUIcOMPUTADOR AS SAL_FLG_COMPUTADOR,
       SAL.POSSUIdATAsHOW AS SAL_FLG_DATA_SHOW ,
       SAL.POSSUIqUADRObRANCO AS SAL_FLG_QUADRO_BRANCO,
       SAL.OBSERVACAO AS SAL_OBSERVACAO,
       SAL.STATUS AS SAL_STATUS
       FROM TB_DISCIPLINA DIS
       INNER JOIN TB_SALA SAL ON SAL.ID = DIS.SALA_ID
       INNER JOIN TB_PROFESSOR PROF ON PROF.ID = DIS.PROFESSOR_ID
       INNER JOIN TB_PESSOA PES_PROF ON PES_PROF.ID = PROF.ID
       LEFT JOIN TB_DISCIPLINA_ALUNO DTA ON DTA.disciplina_id = DIS.ID
       LEFT JOIN TB_ALUNO ALU ON ALU.ID = DTA.ALUNO_ID
       LEFT JOIN TB_PESSOA PES_ALU ON PES_ALU.ID = ALU.ID
       ORDER BY DIS.CURSO, DIS.NOME
